source ~/.zsh-plugins.sh 
source ~/.dotfiles/zsh/env.zsh
source ~/.dotfiles/zsh/options.zsh
source ~/.dotfiles/zsh/bindings.zsh
source ~/.dotfiles/zsh/aliases.zsh


[[ -s "/home/fculpo/.gvm/scripts/gvm" ]] && source "/home/fculpo/.gvm/scripts/gvm"
