source ~/.zsh-plugins.sh 
source ~/.dotfiles/zsh/env.zsh
source ~/.dotfiles/zsh/options.zsh
source ~/.dotfiles/zsh/bindings.zsh
source ~/.dotfiles/zsh/aliases.zsh

# Load local dotfiles (not versioned)
if [[ -a ~/.*.zsh.local ]]; then
  source ~/.*.zsh.local
fi

[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"
